task: is_open_ended
dataset_path: 'eve-esa/llama-rag'
test_split: 'train'
doc_to_target: !function gpt_preference.create_context_prompt
process_results: !function utils.process_results
metric_list:
  - metric: 'win'
    aggregation: mean
    higher_is_better: true
metadata:
  version: 2.0
dataset_kwargs:
  trust_remote_code: true
