task: gpt_preference
dataset_path: 'eve-esa/llama-rag'
test_split: 'train'
doc_to_text: !function utils.create_context_prompt
doc_to_target: '{{original_answer}}'
process_results: !function utils.process_results
apply_chat_template: true
metric_list:
  - metric: 'win'
    aggregation: mean
    higher_is_better: true
metadata:
  version: 2.0
dataset_kwargs:
  trust_remote_code: true
