task: is_mcqa
dataset_path: 'eve-esa/eve-is-mcqa'
test_split: 'train'
doc_to_text: !function utils.doc_to_text
doc_to_target: 'output'
process_docs: !function utils.process_dataset
process_results: !function utils.process_results
gen_prefix: 'Answer: '
description: 'The following are multiple choice questions (with answers) about EO.\n'
metric_list:
  - metric: "IoU"
    aggregation: mean
    higher_is_better: true
  - metric: "acc"
    aggregation: mean
    higher_is_better: true
metadata:
  version: 2.0
dataset_kwargs:
  trust_remote_code: true
num_fewshot: 2
fewshot_split: 'train'
fewshot_config:
  sampler: first_n
