task: mcqa_single_default
dataset_path: 'eve-esa/mcqa-single-answer'
test_split: 'train'
doc_to_text: !function utils_mcqa_default.doc_to_text
doc_to_target: '{{Answer}}'
process_results: !function utils_mcqa_default.process_results
gen_prefix: 'Answer: '
description: 'Multiple choice questions about Earth Observation. Select the correct answer. Response format: letter only (e.g., "B").'
metric_list:
  - metric: "acc"
    aggregation: mean
    higher_is_better: true
generation_kwargs:
  until:
    - "</s>"
    - "<|im_end|>"
metadata:
  version: 1.0
dataset_kwargs:
  trust_remote_code: true
fewshot_split: 'train'
fewshot_config:
  sampler: first_n
