task: open_ended_w_context
dataset_path: 'eve-esa/open-ended-w-context'
test_split: 'train'
doc_to_text: !function utils_open.doc_to_text
doc_to_target: '{{Answer}}'
gen_prefix: 'A: '
description: "Answer these questions using the provided documents:\n"
process_results: !function utils_open.process_results
metric_list:
  - metric: llm_as_judge
    aggregation: !function utils_open.aggregate_llm_judge
    higher_is_better: true
    alias: llm_judge
generation_kwargs:
  until:
    - "</s>"
    - "<|im_end|>"
  max_gen_toks: 40000
metadata:
  version: 2.1
dataset_kwargs:
  trust_remote_code: true
fewshot_split: 'train'
fewshot_config:
  sampler: first_n
