task: open_ended_w_context
class: !function task.OpenEndedWContextTask
output_type: generate_until
dataset_path: 'eve-esa/open-ended-w-context'
test_split: 'train'
doc_to_target: '{{Answer}}'
gen_prefix: 'A: '
description: "Answer these questions using the provided documents:\n"
generation_kwargs:
  until:
    - "</s>"
    - "<|im_end|>"
  add_generation_prompt: false
  continue_final_message: true
metadata:
  version: 2.1
dataset_kwargs:
  trust_remote_code: true
fewshot_split: 'train'
fewshot_config:
  sampler: first_n
