task: tr_open_ended
dataset_path: 'eve-esa/tr_open_ended'
test_split: 'train'
doc_to_text: !function utils_open.doc_to_text_tr
doc_to_target: '{{Answer}}'
gen_prefix: 'A: '
description: "Answer these questions using the provided document:\n"
process_results: !function utils_open.process_results
output_type: generate_until
generation_kwargs:
   until:
     - <|im_end|>
   max_gen_toks: 50000
metric_list:
  - metric: llm_judge_future
    aggregation: !function utils_open.aggregate_llm_judge
    higher_is_better: true
    alias: llm_judge

metadata:
  version: 2.1
dataset_kwargs:
  trust_remote_code: true
num_fewshot: 2
fewshot_split: 'train'
fewshot_config:
  sampler: first_n
