task: mcqa_multiple_answer
dataset_path: 'eve-esa/mcqa-multiple-answer'
test_split: 'train'
doc_to_text: !function utils_mcqa.doc_to_text
doc_to_target: 'output'
process_docs: !function utils_mcqa.process_dataset
process_results: !function utils_mcqa.process_results
gen_prefix: 'Answer: '
description: 'The following are multiple choice questions (with answers) about EO.\n Answer the questions by choosing one or more of the provided options. Start your answer with the letter(s) corresponding to your choice(s). If there are multiple correct answers, list all correct options, separated by a comma, without any additional text.\n'
metric_list:
  - metric: "IoU"
    aggregation: mean
    higher_is_better: true
  - metric: "acc"
    aggregation: mean
    higher_is_better: true
generation_kwargs:
  until:
    - "</s>"
    - "<|im_end|>"
  max_gen_toks: 40000
metadata:
  version: 2.1
dataset_kwargs:
  trust_remote_code: true
fewshot_split: 'train'
fewshot_config:
  sampler: first_n
