task: refusal
dataset_path: 'eve-esa/refusal'
test_split: 'train'
doc_to_text: !function utils_open.doc_to_text
doc_to_target: "I'm sorry, but the provided context does not contain enough information to answer that question."
gen_prefix: 'A: '
description: "Answer these questions using the provided documents:\n"
process_results: !function utils_open.process_results
metric_list:
  - metric: llm_as_judge
    aggregation: !function utils_open.aggregate_llm_judge
    higher_is_better: true
    alias: llm_judge
metadata:
  version: 2.1
dataset_kwargs:
  trust_remote_code: true
fewshot_split: 'train'
fewshot_config:
  sampler: first_n
