"dataset_name": "earth_observation_and_earth_sciences"
"tag": "earth_observation_and_earth_science_refusal"
"include": "_sapien_open_ended_template_yaml"
"task": "earth_observation_and_earth_sciences_refusal"
