dataset: eve-esa/sapien_open_ended
split: train
subset: lidar
task_name: test
model:
  model_name: "openai/gpt-4o-mini"
  temperature: 0.3
  max_tokens: 30000
  base_url: "https://openrouter.ai/api/v1"
  api_key: ''
  prompt: |
    Answer the following question:
    {Question}
  response_model:
    answer: str
judge:
  model_name: "openai/gpt-4o-mini"
  temperature: 0.3
  max_tokens: 30000
  base_url: "https://openrouter.ai/api/v1"
  api_key: ''
  prompt: |
    You will be given a Question and a Provided Answer. Judge whether the Provided Answer is correct by comparing it to the Reference Answer. Differently formatted dates, people with missing middle names, and alternative spellings should all be considered the same.
  
    Question: "{Question}"
    Provided Answer: "{model_answer}"
    Reference Answer: "{Answer}"
  response_model:
    correct: bool
