task: open_ended
dataset_path: 'eve-esa/open-ended'
test_split: 'train'
doc_to_text: "Q: {{Question}}\n"
doc_to_target: '{{Answer}}'
gen_prefix: 'A: '
description: "Answer these questions:\n"
process_results: !function utils_open.process_results
metric_list:
  - metric: llm_as_judge
    aggregation: !function utils_open.aggregate_llm_judge
    higher_is_better: true
    alias: llm_as_judge
generation_kwargs:
  until:
    - "</s>"
    - "<|im_end|>"
  max_gen_toks: 40000
metadata:
  version: 2.1
fewshot_split: 'train'
fewshot_config:
  sampler: first_n
