task: open_ended
class: !function task.OpenEndedTask
output_type: generate_until
dataset_path: 'eve-esa/open-ended'
test_split: 'train'
doc_to_text: "Q: {{Question}}\n"
doc_to_target: '{{Answer}}'
gen_prefix: 'A: '
description: "Answer these questions:\n"
generation_kwargs:
  until:
    - "</s>"
    - "<|im_end|>"
  add_generation_prompt: false
  continue_final_message: true
metadata:
  version: 2.1
fewshot_split: 'train'
fewshot_config:
  sampler: first_n
