task: sapien_open_ended
dataset_path: 'eve-esa/eve-2k-open-ended'
test_split: 'train'
doc_to_text: "Q: {{Question}}\n"
doc_to_target: '{{Answer}}'
gen_prefix: 'A: '
description: "Answer these questions:\n"
process_results: !function utils_open.process_results2
metric_list:
  - metric: llm_judge_future
    aggregation: !function utils_open.aggregate_llm_judge
    higher_is_better: true
    alias: llm_judge

metadata:
  version: 2.1
dataset_kwargs:
  trust_remote_code: true
num_fewshot: 2
fewshot_split: 'train'
fewshot_config:
  sampler: first_n
