group: sapien_open_ended
task:
  - atmospheric_observations
  - earth_monitoring
  - earth_observation_and_earth_sciences
  - environmental_monitoring
  - geospatial_monitoring
  - land_use_land_cover
  - lidar
  - miscellaneous
  - multispectral_imaging
  - remote_sensing
  - satellite_observation
  - synthetic_aperture_radar
aggregate_metric_list:
  - metric: llm_judge_future
    weight_by_size: True
    aggregation: mean