task: ts_open_ended
dataset_path: 'eve-esa/qa_translated_pilot'
test_split: 'train'
doc_to_text: "Q: {{question}}\n"
doc_to_target: '{{answer}}'
gen_prefix: 'A: '
description: "Answer these questions:\n"
process_results: !function utils_open.process_results
metric_list:
  - metric: llm_judge_future
    aggregation: !function utils_open.aggregate_llm_judge
    higher_is_better: true
    alias: llm_judge

metadata:
  version: 2.1
dataset_kwargs:
  trust_remote_code: true
num_fewshot: 5
fewshot_split: 'train'
fewshot_config:
  sampler: first_n
