task: user_type_qa
dataset_path: eve-esa/user_type_qa
test_split: 'train'
doc_to_text: "Q: {{Question}}\n"
doc_to_target: '{{Answer}}'
gen_prefix: 'A: '
description: "Answer these questions:\n"
process_results: !function utils_open.process_results2
metric_list:
  - metric: llm_judge_future
    aggregation: !function utils_open.aggregate_llm_judge
    higher_is_better: true
    alias: llm_judge
generation_kwargs:
  until:
    - "</s>"
filter_list:
  - name: get_response
    filter:
      # Filter everything after the first break line
      - function: "regex"
        regex_pattern: "^\\s*(?:A:\\s*)?([\\s\\S]*?\\S)\\s*$"
      - function: take_first
metadata:
  version: 1.0
dataset_kwargs:
  trust_remote_code: true
num_fewshot: 5
fewshot_split: 'train'
fewshot_config:
  sampler: first_n
