task: mcqa_single_answer
dataset_path: 'eve-esa/mcqa-single-answer'
test_split: 'train'
doc_to_text: !function utils_mcqa_single.doc_to_text
doc_to_target: '{{Answer}}'
process_results: !function utils_mcqa_single.process_results
gen_prefix: 'Answer: '
description: 'The following are multiple choice questions (with answers) about EO.\n Answer the question by choosing one of the provided options. Start your answer with the letter corresponding to your choice, without any additional text.\n'
metric_list:
  - metric: "acc"
    aggregation: mean
    higher_is_better: true
generation_kwargs:
  until:
    - "</s>"
    - "<|im_end|>"
  max_gen_toks: 40000
metadata:
  version: 2.1
dataset_kwargs:
  trust_remote_code: true
fewshot_split: 'train'
fewshot_config:
  sampler: first_n
