task: mcqa_multiple_default
dataset_path: 'eve-esa/mcqa-multiple-answers'
test_split: 'train'
doc_to_text: !function utils_mcqa_default.doc_to_text
doc_to_target: 'output'
process_docs: !function utils_mcqa_default.process_dataset
process_results: !function utils_mcqa_default.process_results
gen_prefix: 'Answer: '
description: 'Multiple choice questions about Earth Observation. Select the correct answer(s). Some questions have one answer, others have multiple. Be precise. Response format: letter(s) only (e.g., "B" or "A, C, D").'
metric_list:
  - metric: "IoU"
    aggregation: mean
    higher_is_better: true
  - metric: "acc"
    aggregation: mean
    higher_is_better: true
generation_kwargs:
  until:
    - "</s>"
    - "<|im_end|>"
metadata:
  version: 1.0
dataset_kwargs:
  trust_remote_code: true
fewshot_split: 'train'
fewshot_config:
  sampler: first_n
