task: eo_summarization
dataset_path: 'eve-esa/summarization_ds_10k_sample_split'
test_split: 'dev'
doc_to_text: 'Summarize the following document: \n{{input}}'
doc_to_target: '{{output}}'
gen_prefix: 'Summary: '
process_results: !function utils_sum.process_results
metric_list:
  - metric: llm_judge
    aggregation: !function utils_sum.aggregate_mean_score
    higher_is_better: true
  - metric: relevance
    aggregation: !function utils_sum.aggregate_mean_score
    higher_is_better: true
  - metric: coherence
    aggregation: !function utils_sum.aggregate_mean_score
    higher_is_better: true
  - metric: factuality
    aggregation: !function utils_sum.aggregate_mean_score
    higher_is_better: true
  - metric: conciseness
    aggregation: !function utils_sum.aggregate_mean_score
    higher_is_better: true

metadata:
  version: 2.1
dataset_kwargs:
  trust_remote_code: true
